### PR TITLE
Ignore the egg and pyc files.

### PR DESCRIPTION
**Pull request by bowlofeggs**

### CODE REVIEW

**Comment by jpwoodbu** [comment]
I'm a bit of a git n00b, but I've always found it strange that ignore configs end up in repos. Is this not considered a personal configuration?

**Comment by rbarlow** [comment]
On Wed, Dec 16, 2015 at 05:01:01PM -0800, Jonathan Woodbury wrote:
> I'm a bit of a git n00b, but I've always found it strange that ignore configs end up in repos. Is this not considered a personal configuration?

pycs are a build artifact, so it would always be incorrect for them to
get included in a repository. By adding them to the gitignore file, it
guarantees that they will not get committed accidentally by anyone.

P.S. I'll respond to your change requests soon, perhaps tonight!

-- 
Randy Barlow
irc:   bowlofeggs
phone: +1-919-890-8150

**Comment by jpwoodbu** [comment]
Was there something that happened that made you want to include this config in the repo? I've never felt I needed it. In the name of discovery, I'm tempted to wait and see if I later find I want this config in the repo.

**Comment by rbarlow** [comment]
On Sun, Dec 20, 2015 at 03:37:27PM -0800, Jonathan Woodbury wrote:
> Was there something that happened that made you want to include this config in the repo? I've never felt I needed it. In the name of discovery, I'm tempted to wait and see if I later find I want this config in the repo.

Not really, but it is a pretty good idea to try to prevent pull requests
from accidentally including what are essentially build files. I believe
it's common practice to add .gitignore files to projects that exclude
build artifacts.

There isn't a specific problem that is happening now, it's more of a
future-proofing sort of thing.

-- 
Randy Barlow
irc:   bowlofeggs

**Comment by robled** [comment]
I like to think of an included .gitignore as an automated, documented way in which everyone agrees that certain types of files/dirs will never be included in the repo.

**Pull request merged**
